# Generated by Django 4.0.6 on 2022-09-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_voucher', models.CharField(max_length=10)),
                ('activation_code', models.CharField(max_length=17)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('id_card_code', models.IntegerField(blank=True, null=True)),
                ('bank_card_num', models.IntegerField(blank=True, null=True)),
                ('shaba_num', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(default='profile/avatar-svgrepo-com.svg', upload_to='profile/avatar/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='profile/id_card/')),
                ('bank_card_pic', models.ImageField(blank=True, null=True, upload_to='profile/bank_card/')),
                ('vip_user', models.BooleanField(default=False)),
                ('id_card_status', models.CharField(choices=[('to do', 'To Do'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('ok', 'Ok')], default='to do', max_length=255)),
                ('bank_card_pic_status', models.CharField(choices=[('to do', 'To Do'), ('in_progress', 'In Progress'), ('failed', 'Failed'), ('ok', 'Ok')], default='to do', max_length=255)),
                ('ticket_sum', models.IntegerField(default=0)),
                ('buy_sum', models.IntegerField(default=0)),
                ('sell_sum', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
