# Generated by Django 4.0.6 on 2022-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
