# Generated by Django 4.0.6 on 2022-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dollarpricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarpricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
