# Generated by Django 4.0.6 on 2022-12-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
