# Generated by Django 4.0.6 on 2022-12-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticketshowstatus_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketShowStatus',
        ),
        migrations.CreateModel(
            name='Sd',
            fields=[
            ],
            options={
                'verbose_name': 'fsdf',
                'verbose_name_plural': 'fsdf',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket.ticket',),
        ),
    ]
