# Generated by Django 4.0.6 on 2022-12-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_delete_ticketshowstatus_sd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sd',
        ),
        migrations.CreateModel(
            name='TicketProxy',
            fields=[
            ],
            options={
                'verbose_name': '1',
                'verbose_name_plural': '1',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ticket.ticket',),
        ),
    ]
