# Generated by Django 4.0.6 on 2022-12-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_delete_sd_ticketproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketProxy',
        ),
    ]
