# Generated by Django 4.0.6 on 2022-12-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reply',
        ),
        migrations.AlterField(
            model_name='replyticket',
            name='rep_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
