# Generated by Django 4.0.6 on 2022-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbuy',
            name='condition',
            field=models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending'), ('null', 'Null')], default='null', max_length=255),
        ),
    ]
