# Generated by Django 4.0.6 on 2022-12-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderbuy_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbuy',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
